package com.bridgelabz.bannerapp;

/**
 * UC2: Render OOPS Banner using Print Statements
 *
 * This class demonstrates printing an OOPS banner to the console using
 * ASCII art style. Each line of the banner is printed using separate
 * System.out.println statements.
 * <p>Banner is generated by printing predefined string patterns line by line
 * to form the letters O, O, P, and S in a style that resembles a banner.
 * This example showcases basic console output in Java.
 * </p>
 *
 * @author Bridgelabz
 * @version 2.0
 */

public class PrintOOPSBanner {
    // Main method to print the OOPS banner
    // Each line of the banner is printed using separate print statements
    // to create the desired ASCII art representation.
    // No input parameters are required for this method.
    // The output is directly printed to the console.
    // Time Complexity: O(1) - Fixed number of print statements
    // Space Complexity: O(1) - No additional data structures used

    public static void main(String[] args) {
        System.out.println("   ***       ***    ******     ****** ");
        System.out.println(" **   **   **   **  **    ** **       ");
        System.out.println("**     ** **     ** **    ** **       ");
        System.out.println("**     ** **     ** *******   ******* ");
        System.out.println("**     ** **     ** **              **");
        System.out.println(" **   **   **   **  **              **");
        System.out.println("   ***       ***    **        ******* ");
    }
}